### ISSUE TITLE
윈도우10에서 설치후 실행시 error가 발생합니다

### ISSUE THREAD

**Issue by pmankyu** [kaluma-project/kaluma-agent#20]
윈도우 10에서 kaluma-agent 설치후 실행하면 다음 에러가 발생합니다

![image](https://user-images.githubusercontent.com/6636556/143184211-d8f88759-0b9c-4c73-b567-92706842ff53.png)

확인 누르면 종료되는데 작업관리자에서 보면 아래와 같이 살아 있습니다
![image](https://user-images.githubusercontent.com/6636556/143184378-79e670bf-571c-48bd-a7a8-f756d6480f33.png)

반복실행하면 동일 에러 출력후 작업관리자에 추가 생성되있는것을 볼수 있습니다

![image](https://user-images.githubusercontent.com/6636556/143184553-9186d4fc-44f4-4a74-b89c-b7637fb76cfc.png)

혹시 미리 설치해줘야 하는 패키지 같은것이 있을까요?

**Comment by niklauslee** [comment]
중복적으로 실행하신것 같습니다. 기본적으로 운영체제 부팅시 자동으로 실행됩니다. 따로, 실행할 필요는 없습니다.

**Comment by pmankyu** [comment]
알겠습니다~!
